### ISSUE TITLE
Shows up on every right-click menu

### ISSUE THREAD

**Issue by haarp** [Mathnerd314/repagination#3]
When right-clicking an empty space, Repagination shows up. It should only show up when right-clicking links.

**Comment by Mathnerd314** [comment]
It's easy enough to add a [link context](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/ContextType) to the Load all and Limited items. The issue is 'Stop!'. The old behavior was to hide it when Repagination wasn't running, but there's no WebExtension API for that [yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1215376), hence the current behavior of just always showing the menu.

**Comment by Mathnerd314** [comment]
Turns out that API wasn't necessary, new version shows stop only when Re-pagination is running. It does show up in all tabs, rather than just the one it's running in, but that should be fine. And then the other  items only show up on links now.
